/**
 * @author spindyzel
 * @since 28 Desember 2019
*/

const CONSTANTS = {
    COOKIE_TOKEN_KEY: 'AUTHENTICATION-KEY',
    ORIGINAL_TOKEN_KEY: 'AUTHORIZATION-KEY',
    HOME_MENU_KEY: 'HOME',
    LOGIN_MENU_KEY: 'LOGIN',
    PANITIA_MENU_KEY: 'PANITIA',
    ADMIN_MENU_KEY:'ADMIN',
    SIGNER_MENU_KEY:'SIGNER',
    ACTIVE_EVENT_MENU_KEY :'ACTIVE_EVENT',
    PARTICIPANT_EVENT_MENU_KEY :'PARTICIPANT_EVENT',
    DETAIL_EVENT_PANITIA_MENU_KEY : 'DETAIL_EVENT_PANITIA',
    DETAIL_SERTIF_PANITIA_MENU_KEY : 'DETAIL_SERTIF_PANITIA'
};

export default CONSTANTS;