/**
 * @author spindyzel
 * @since 28 Desember 2019
*/

const CONSTANTS = {
    COOKIE_TOKEN_KEY: 'AUTHENTICATION-KEY',
    ORIGINAL_TOKEN_KEY: 'AUTHORIZATION-KEY',
    HOME_MENU_KEY: 'HOME',
    ALL_EVENT_MENU_KEY: 'ALL_EVENT',
    ALL_KATEGORI_MENU_KEY: 'ALL_KATEGORI',
    LOGIN_MENU_KEY: 'LOGIN',
    PROFILE_MENU_KEY: 'PROFILE',
    EDIT_PROFILE_MENU_KEY : 'EDIT_PROFILE',
    REGISTER_PANITIA_KEY : 'REGISTER_PANITIA',
    REGISTER_PESERTA_KEY : 'REGISTER_PESERTA',
    CHOOSE_MENU_KEY : 'CHOOSE',
    LIST_EVENT_MENU_KEY : 'LIST_EVENT',
    FORGET_PASSWORD_MENU_KEY : 'FORGET_PASSWORD',
    EDIT_PASSWORD_MENU_KEY : 'EDIT_PASSWORD',
    //dashboard Panitia

    //active event
    ACTIVE_EVENT_MENU_KEY :'ACTIVE_EVENT',
    PARTICIPANT_EVENT_MENU_KEY :'PARTICIPANT_EVENT',
    DETAIL_LIST_PARTICIPANT_EVENT_MENU_KEY : 'DETAIL_LIST_PARTICIPANT_EVENT',
    DETAIL_EVENT_PANITIA_MENU_KEY : 'DETAIL_EVENT_PANITIA',
    EDIT_EVENT_PANITIA_MENU_KEY : 'EDIT_EVENT_PANITIA',

    //history event
    DETAIL_LIST_PARTICIPANT_HISTORY_EVENT_MENU_KEY : 'DETAIL_LIST_PARTICIPANT_HISTORY_EVENT',
    DETAIL_HISTORY_EVENT_PANITIA_MENU_KEY : 'DETAIL_HISTORY_EVENT_PANITIA',

    //sertifikat
    EDIT_SERTIF_PANITIA_MENU_KEY : 'EDIT_SERTIF_PANITIA',
    WAITING_SERTIF_PANITIA_MENU_KEY : 'WAITING_SERTIF_PANITIA',
    LIST_SERTIF_PANITIA_MENU_KEY : 'LIST_SERTIF_PANITIA',
    PENGAJUAN_SERTIF_PANITIA_MENU_KEY : 'PENGAJUAN_SERTIF_PANITIA',

    PANITIA_MENU_KEY: 'PANITIA',
    LIST_PARTICIPANT_EVENT_MENU_KEY : 'LIST_PARTICIPANT_EVENT',
    EDIT_PASSWORD_PANITIA_MENU_KEY : 'EDIT_PASSWORD_PANITIA',
    
    DETAIL_EVENT_KEY : 'DETAIL_EVENT',
    ADMIN_MENU_KEY:'ADMIN',
    BIODATA_PENANDATANGAN_ADMIN_KEY : 'BIODATA_PENANDATANGAN_ADMIN',
    LIST_BIODATA_PENANDATANGAN_PANITIA_MENU_KEY : 'LIST_BIODATA_PENANDATANGAN',
    CREATE_BIODATA_PENANDATNAGAN_MENU_KEY : 'CREATE_BIODATA_PENANDATNAGAN',
    SIGNER_MENU_KEY:'SIGNER',
    PROFILE_SIGNER_MENU_KEY : 'PROFILE_SIGNER',
    EDIT_PASSWORD_SIGNER_MENU_KEY : 'EDIT_PASSWORD_SIGNER',
    
    PROFILE_ADMIN_PANITIA_MENU_KEY : 'PROFILE_ADMIN_PANITIA',
   
    EDIT_PROFILE_PANITIA_MENU_KEY : 'EDIT_PROFILE_PANITIA',
    EDIT_PROFILE_SIGNER_MENU_KEY : 'EDIT_PROFILE_SIGNER',
    EDIT_PROFILE_PESERTA_MENU_KEY : 'EDIT_PROFILE_PESERTA',
    DETAIL_SERTIF_PANITIA_MENU_KEY : 'DETAIL_SERTIF_PANITIA',
    DETAIL_SERTIF_SIGNER_MENU_KEY : 'DETAIL_SERTIF_SIGNER',
    DETAIL_PESERTA_ADMIN_MENU_KEY : 'DETAIL_PESERTA_ADMIN',
    DETAIL_PANITIA_ADMIN_MENU_KEY : 'DETAIL_PANITIA_ADMIN',
    DETAIL_PENANDATANGAN_ADMIN_MENU_KEY : 'DETAIL_PENANDATANGAN_ADMIN',
    EDIT_PENANDATANGAN_ADMIN_MENU_KEY : 'EDIT_PENANDATANGAN_ADMIN',
    EDIT_PANITIA_ADMIN_MENU_KEY : 'EDIT_PANITIA_ADMIN',
    DETAIL_EVENT_ADMIN_MENU_KEY :'DETAIL_EVENT_ADMIN',
    DETAIL_EVENT_PESERTA_MENU_KEY : 'DETAIL_EVENT_PARTICIPANT_PANITIA',
    DETAIL_PESERTA_EVENT_MENU_KEY : 'DETAIL_PESERTA_EVENT',
    DAFTAR_PENANDATANGAN_MENU_KEY : 'DAFTAR_PENANDATANGAN',
    LIST_WAITING_SERTIFIKAT_ADMIN_MENU_KEY : 'LIST_WAITING_SERTIFIKAT_ADMIN',
    DETAIL_LIST_ALL_EVENT_MENU_KEY : 'DETAIL_LIST_ALL_EVENT',
    DETAIL_APPROVAL_EVENT_MENU_KEY : 'DETAIL_APPROVAL_EVENT',
};

export default CONSTANTS;