const CONSTANTS = {
    COOKIE_TOKEN_KEY: 'AUTHENTICATION-KEY',
    ORIGINAL_TOKEN_KEY: 'AUTHORIZATION-KEY',
    HOME_MENU_KEY: 'HOME',
    LOGIN_MENU_KEY: 'LOGIN',
    DASHBOARD_MENU_KEY: 'DASHBOARD',
};

export default CONSTANTS;